version: '3.9'

services:
  vms-web:
    image: vtpl/vms-web-new:1.0
    container_name: vms-web
    restart: always
    ports:
      - '8080:8080' # HTTP on 800
      - '8443:8443' # HTTPS on 8443
    volumes:
      - ./ssl:/etc/nginx/ssl
