# ----------------------
# HTTP server (port 80)
# ----------------------
server {
    listen 800;
    listen [::]:800;

    server_name apiservice.videonetics.com;

    root /usr/share/nginx/html;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /index.html;
}

# ----------------------
# HTTPS server (port 443)
# ----------------------
server {
    listen 8443 ssl;
    listen [::]:8443 ssl;

    server_name apiservice.videonetics.com;

    # SSL certificates
    ssl_certificate		/etc/nginx/ssl/videonetics.cer;
    ssl_certificate_key	/etc/nginx/ssl/videonetics.key;

    root /usr/share/nginx/html;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /index.html;
}