import { environment } from '../../environments/environment';

export const API_ENDPOINTS = {
  LOGIN: `${environment.apiBaseUrl}user/login`,
  SIGNIN: `${environment.apiBaseUrl}user/signin`,
  FORGOT_PASSWORD: `${environment.apiBaseUrl}user/forgotpassword/generatelink`,
  RESET_PASSWORD: `${environment.apiBaseUrl}user/forgotpassword/reset`,
  VALIDATE_KEY: `${environment.apiBaseUrl}user/forgotpassword/validate/{uniquekey}`,
  LOCATION_TREE: `${environment.apiBaseUrl}{serverid}/channel/junction/tree`,
  CHANNEL_STATUS: `${environment.apiBaseUrl}{serverid}/channel/channel/status`,
  SERVER_INFO: `${environment.apiBaseUrl}server`,
  USER_SESSION: `${environment.apiBaseUrl}user/session`,
  SERVER_CONFIG: `${environment.apiBaseUrl}server/config`,
  ANALYTICS_INFO: `${environment.apiBaseUrl}{serverid}/analytic/type`,
  KEEP_ALIVE_LIVE: `${environment.apiBaseUrl}{serverid}/live/keepalive`,
  WEBRTC_LIVE: `${environment.apiBaseUrl}webrtc/{serverid}/startlive`,
  HLS_START_LIVE: `${environment.apiBaseUrl}{serverid}/startlive`,
  HLS_STOP_LIVE: `${environment.apiBaseUrl}{serverid}/stoplive`,
  KEEP_ALIVE_ARCHIVE: `${environment.apiBaseUrl}{serverid}/archive/keepalive`,
  WEBRTC_ARCHIVE: `${environment.apiBaseUrl}webrtc/{serverid}/startarchive`,
  HLS_START_ARCHIVE: `${environment.apiBaseUrl}{serverid}/startarchive`,
  STOP_ARCHIVE: `${environment.apiBaseUrl}{serverid}/stoparchive`,
  ENCODED_START_ARCHIVE: `${environment.apiUrl}/V2.2/archive/playback-url/start/resource-server/V1/REST/{serverid}/`,
  ENCODED_STOP_ARCHIVE: `${environment.apiUrl}/V2.2/archive/playback-url/stop/resource-server/`,
  VIDEO_INFO: `${environment.apiBaseUrl}{serverid}/channel/getstreamingparameter/{channelid}/{streamindex}`,
  ARCHIVE_BARCLIP: `/barclip/`,
  ARCHIVE_MOTIONCLIP: `/motionclip/`,
  CHANNEL_INFO: `${environment.apiBaseUrl}{serverid}/channel`,
  EVENT_SEARCH: `${environment.apiBaseUrl}{serverid}/event/getevents`,
  EVENT_COUNT: `${environment.apiBaseUrl}{serverid}/event/count`,
  USER_INFO: `${environment.apiBaseUrl}user`,
  UPDATE_USER: `${environment.apiBaseUrl}user/update/details`,
  CHANGE_PASSWORD: `${environment.apiBaseUrl}user/changepassword`,
};
